### PR TITLE
Issue 215 Add order parameter to Showkase annotation

### PR DESCRIPTION
**Pull request by themanol**
Adding a parameter to the Showkase Annotations that allow customise the order of the element in the ShowkaseBrowser.
Screenshot 2022-01-25 at 16 38 17

### CODE REVIEW

**Comment by themanol** [comment]
Hi, do you think this could be interesting for merging in the next release? thanks!

**Comment by marcorighini** [comment]
This looks like an interesting improvement to give the possibility to order the components.
Is there a plan to merge it @vinaygaba ?

**Comment by vinaygaba** [comment]
@marcorighini I'm not a fan of adding so many one off properties to `@ShowkaseComposable`. It's not elegant - moreover, Showkase exposes all your previews that it collects through the `Showkase.getMetadata()` function (more info here - https://github.com/airbnb/Showkase#5-showkase-object). Using this metadata object, it would be trivial to create your own browser that behaves exactly how you want it to behave.

**Comment by vinaygaba** [comment]
Closing this PR as I think using the Showkase metadata API for creating a custom browser for your use cases might be a better approach.

**Pull request closed without merging**
