### PR TITLE
Update gradle version and android gradle plugin version

### PR DESCRIPTION
**Pull request by karanDhillon**
### Changes
* Update Gradle version from `6.7` to `6.8-rc-1`.
* Update Android Gradle Plugin version from `4.2.0-alpha15` to `7.0.0-alpha04`.

### CODE REVIEW

**Comment by karanDhillon** [comment]
```
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
```
Not sure if this is a requirement for AS gradle plugin `7.0.0-alpha04` or is happening due to the CI environment.

**Comment by vinaygaba** [comment]
@karanDhillon I'll have to pull your branch and test it out. Btw, did that issue you filed get resolved?

**Comment by karanDhillon** [comment]
> @karanDhillon I'll have to pull your branch and test it out. Btw, did that issue you filed get resolved?

@vinaygaba Issue #126 is still `open`. However, to upgrade the `Gradle version` and `Android Gradle plugin version` and to make sure it compiles, I removed the **test dependencies** (specifically `testImplementation files(getRuntimeJar())` and `testImplementation files(Jvm.current().getToolsJar())`) in question for module `showcase-processor-testing`.

**Comment by karanDhillon** [comment]
Found [this](https://www.reddit.com/r/androiddev/comments/k6izfp/psa_android_gradle_plugin_70_will_require_java_11/) over reddit. TL;DR: AGP `7.0` will require JAVA `11`. However, the `sample` module `build.gradle` script's is targeting JAVA 1.8:
```
compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
```
@vinaygaba We can try to upgrade to JAVA `11`, and see if `sample` module passes CI compile check or not (given desugaring works to support min SDK `21`).

**Comment by vinaygaba** [comment]
@karanDhillon I'm totally open to using Java11 but it would require using Arctic Fox for developing in this repo. If you are already using it, just update this PR and update the dependencies to use Java 11.

**Comment by karanDhillon** [comment]
@vinaygaba sounds good, will update every module to use JAVA `11`, and push the changes here. Thanks 👍🏻 !

**Comment by vinaygaba** [comment]
@karanDhillon You sir, are a legend!

**Comment by karanDhillon** [comment]
> @karanDhillon You sir, are a legend!

Means a lot to receive a compliment from you @vinaygaba 🙏🏻 !

### Changes
* `sourceCompatibility` and `targetCompatibility` set to JAVA `11`.
*  Kotlin source code will be compiled to JAVA `11` as well.
* Android SDK build tools updated to `Build Tools, Revision 30.0.0 rc4` to support Android `11` APIs.
*  Android Studio Arctic Fox | 2020.3.1 Canary 4 did not had JDK 11 embedded, so OpenJDK 11 was used in the local environment.

**Comment by karanDhillon** [comment]
CI build failing potentially due to Issue #126, as same `NPE` is getting thrown.

**Comment by vinaygaba** [comment]
This PR resolves the Java 11 issue - https://github.com/airbnb/Showkase/pull/145

**Comment by karanDhillon** [comment]
@vinaygaba LGTM 🎉 !

PS: Thanks you fixing the JDK 11 issue on #145 👍🏻 .

**Pull request closed without merging**
