### PR TITLE
Bump compose compiler to 1.3.1 and libs to 1.2.1

### PR DESCRIPTION
**Pull request by oas004**
In this PR I have bumped the Compose compiler version to 1.3.0 and the libs to 1.2.1 as the latest stable version 😄

This also meant I had to bump the following:

- KSP -> 1.7.10-1.0.6
- Compose activity -> 1.5.1
- Kotlin -> 1.7.10
- KotlinCompilerVersion -> 1.7.10

### CODE REVIEW

**Comment by oas004** [comment]
I guess 1.3.1 is out now? 🤔 @vinaygaba Should I close this or should I try to update to 1.3.1? Wdyt? :)

**Comment by vinaygaba** [comment]
Maybe do it in this PR itself @oas004. Since they both support the same version of kotlin, it should be fine to use the latest one. I hadn't merged this before because I wanted to do a release first (which we already did last month) to make sure people using the older version of Kotlin had a version of Showkase that would work. I think going forward, it's compatible regardless so should be easier for us to do this version bumps

**Comment by oas004** [comment]
> Maybe do it in this PR itself @oas004. Since they both support the same version of kotlin, it should be fine to use the latest one. I hadn't merged this before because I wanted to do a release first (which we already did last month) to make sure people using the older version of Kotlin had a version of Showkase that would work. I think going forward, it's compatible regardless so should be easier for us to do this version bumps

Aha yes that makes sense! I will try to update this PR then 😄

**Comment by oas004** [comment]
@vinaygaba Bumped to target 1.3.1 now :) Tests seems fine and seems fine locally :)

**Review by vinaygaba — APPROVED** [review]

**Pull request merged**
