### PR TITLE
Embed proguard rule for generated provider class

### PR DESCRIPTION
**Pull request by mataku**
## Summary

Embed proguard rules for Codegen class so that minifyEnabled applications do not need additional rules.

Since the Codegen class extends the ShowkaseProvider class, additional rules are unnecessary for each application by providing rules for types that extend the ShowkaseProvider class.

consumerProguardRules is already specified in the project, so I added to it. 
https://github.com/airbnb/Showkase/blob/4a09e3ff1d3ef71c6b151b5c7deefc82529691c0/showkase/build.gradle#L15

refs. https://github.com/airbnb/Showkase/issues/199, https://github.com/airbnb/Showkase/issues/244

## Context

Currently, we need to add extra proguard rules if we set minifyEnabled as true

```kotlin
@ShowkaseRootModule
class SampleShowkaseRootModule : ShowkaseRootModule

// Showkase generated class
public class SampleShowkaseRootModuleCodegen : ShowkaseProvider
```

```shell
# application proguard rules
-keep class **.SampleShowkaseRootModuleCodegen { }
```

### CODE REVIEW

**Review by vinaygaba — APPROVED** [review]
Thanks for the change!

**Comment by mataku** [comment]
@vinaygaba 
There seems to be a problem with ui-testing workflow on GitHub Actions. I think macos-10.15 labelled runner is no longer available, so created a pull request to fix it: https://github.com/airbnb/Showkase/pull/342

Announcement: https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

Available Runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by mataku** [comment]
@vinaygaba 
Thanks for merging https://github.com/airbnb/Showkase/pull/342! Is there anything else I should do?

**Comment by mataku** [comment]
The workflow execution seems to be unstable. The previous commit passed and the latest commit failed. I will look log details

**Comment by vinaygaba** [comment]
@mataku yeah these builds have been flaky and I have not had the time to investigate. Any help on this front will be greatly appreciated 🙏🏻

**Comment by mataku** [comment]
I think this pull request itself doesn't affect CI workflow's result because all projects in Showkase set minifyEnabled as false so generated apk doesn't apply R8 or proguard.

I investigated test results in my forked repo: https://github.com/mataku/Showkase/actions (WIP)

- At first it is rare to encounter failing tests
  - You may see action run count itself is too small in above link, but I retried many times in each runs. 
- encountered com.airbnb.android.showkase_browser_testing.ShowcaseBrowserTest#customAnnotatedPrivateComposablesShouldCompileButNotShow but no logs printed about it
  - https://github.com/mataku/Showkase/actions/runs/5934664335/attempts/33
- sample:connectedDebugAndroidTest often fails (but as noted above, in the first place, it is rare to encounter failing tests)

<details>
<summary> ShowcaseBrowserTest#customAnnotatedPrivateComposablesShouldCompileButNotShow results</summary>

ss- 2023-08-25 14 09 08

</summary>
</details>

**Comment by mataku** [comment]
@vinaygaba 
How about treating instability in CI workflow as a new issue? If possible, I will create a new one.

For some time now, macOS specification on GitHub Actions has been out of date and the CI workflow has not been running, I don't understand the overall problem, but I think it was probably there originally as a potential issue.

In my investigation, the logs are printed unknown state, as if there is a system problem in the output or no logs at all in the first place, and the test will pass in many cases if it is retried. If tests related to changes in a pull request fail, the workflow will fail every time, so you can distinguish between the two.

**Comment by mataku** [comment]
@vinaygaba 

> Additionally, even after removing the tests that were running on API 28

I think you still have left the (deleted) API 28 workflow set as "Require status checks to pass before merging"? Please check the Branch protection rules in Showkase repository settings

<details>
<summary>sample screenshot</summary>

screenshot 2023-08-27 19 37 34

</details>

**Comment by vinaygaba** [comment]
@mataku I've reverted this PR. More explanation on why in the PR I updated it with - https://github.com/airbnb/Showkase/pull/354

**Pull request merged**
